services:
  postgres:
    image: postgres:15
    container_name: repairflow_postgres
    environment:
      POSTGRES_DB: repairflow
      POSTGRES_USER: repair_user
      POSTGRES_PASSWORD: wolf
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: